title: "Illusion Slopes"
author: "Max Kapur"
email: "max@maxkapur.com"
description: >-
  I blog about culture, numerical optimization, and software. I work at a
  consulting firm as an operations research and numerical modeling specialist.
  All opinions are my own.
baseurl: ""  # Site subpath, e.g. /blog
url: "https://maxkapur.com"  # Hostname & protocol, e.g. https://example.com
github_username: "maxkapur"
linkedin_username: "maxkapur"
rss: "via RSS"

# Build settings
excerpt_separator: "<!--more-->"
future: false  # Don't publish posts dated in future
show_excerpts: true  # on homepage

plugins:
  - "jekyll-redirect-from"
  # - "jekyll-paginate"
# paginate: 2
# paginate_path: "blog/page:num"

theme: "minima"

# Select markdown processor. kramdown is the default
markdown: "kramdown"
kramdown:
  math_engine: "katex"  # Let kramdown render KaTeX during build process

# Silence Sass migration warnings as no fix is planned in Minima:
# https://github.com/jekyll/minima/issues/815#issuecomment-2440028795
sass:
  quiet_deps: true

# Exclude from processing (and therefore from _site/)
exclude:
  - ".conda/"
  - "README.md"
  - "**/README.md"
  - "*.sh"
  - "**/*.sh"

# Jekyll also automatically excludes files with a leading underscore in their
# name, as well as the following default excludes:

  # - .sass-cache/
  # - .jekyll-cache/
  # - gemfiles/
  # - Gemfile
  # - Gemfile.lock
  # - node_modules/
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
