baseURL = "https://maxkapur.com"
locale = "en-us"
title = "Illusion Slopes"
theme = "illusion-slopes"

enableGitInfo = true

[frontmatter]
# Extract dates from filenames if possible
date = ["date", ":filename", ":default"]
lastmod = ["lastmod", ":filename", ":default"]
publishDate = ["publishdate", ":filename", ":default"]

[markup.goldmark]
renderer.unsafe = true
