# Site metadata
baseURL = "https://maxkapur.com"
locale = "en-us"
title = "Illusion Slopes"
theme = "illusion-slopes"

# Metadata extraction hints
enableGitInfo = true

# Build settings
cleanDestinationDir = true

[frontmatter]
# Extract dates from filenames if possible
date = ["date", ":filename", ":default"]
lastmod = ["lastmod", ":filename", ":default"]
publishDate = ["publishdate", ":filename", ":default"]

[permalinks]
# For posts (only), include the date in the URL to disambiguate recurring posts
# with the same title (like "recent reading")
posts = "/posts/:year-:month-:day-:slug"

# Shadow the [menus] key from the theme's hugo.toml to suppress "Tags" link, as
# I don't use tags
[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[markup.goldmark]
renderer.unsafe = true
