# Based on https://github.com/actions/upload-pages-artifact

name: build-deploy

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '49 14 * * 3'
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure toolchain (rake configure)
        run: rake configure

      - name: Show package info (rake info)
        run: rake info

      - name: Build site (rake)
        run: rake

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

      - name: Push site build to static branch
        # For portability, maintain a static branch with the site build checked
        # in. This eases deployment to other hosting platforms. Skip this step
        # if running from somewhere other than master.
        if: github.ref == 'refs/heads/master'
        run: |
          git config --local push.autoSetupRemote true
          git switch -C static
          git reset --hard origin/master
          git add -f _site/
          git status
          git commit -m "Automatic site build"
          git push -f

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
