# Based on https://github.com/actions/upload-pages-artifact

name: build-deploy

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '49 14 * * 3'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniforge and Mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ""
          auto-activate-base: true
          channels: conda-forge
          conda-remove-defaults: true
          mamba-version: "*"
          miniforge-version: "latest"

      - name: Configure toolchain (configure.sh)
        shell: bash -el {0}
        run: ./configure.sh

      - name: Show package info (info.sh)
        shell: bash -el {0}
        run: ./info.sh

      - name: Build site (build.sh)
        shell: bash -el {0}
        run: ./build.sh

      - name: Lint (check.sh)
        shell: bash -el {0}
        run: ./check.sh

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
