# Based on https://github.com/actions/upload-pages-artifact

name: build-deploy

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "49 14 * * 3"
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 #v31

      - uses: actions/checkout@v7
        with:
          persist-credentials: true

      - name: Initialize dev shell
        shell: &nix_shell "nix develop --command bash --noprofile --norc -eo pipefail {0}"
        run: echo "Hello"

      - name: Lint
        shell: *nix_shell
        run: ./lint.sh

      - name: Build site
        shell: *nix_shell
        run: hugo build && tree public/

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: public/

      - name: Push site build to static branch
        # For portability, maintain a static branch with the site build checked
        # in. This eases deployment to other hosting platforms. Skip this step
        # if running from somewhere other than master.
        if: github.ref == 'refs/heads/master'
        run: |
          git config --local user.name 'Max Kapur (GitHub Action runner)'
          git config --local user.email 'maxkapur@users.noreply.github.com'
          git config --local push.autoSetupRemote true
          git switch -C static
          git reset --hard origin/master
          git add -f public/
          git status
          git commit -m "Automatic site build"
          git push -f

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
